---
nginx_setup_disable_default_site: true

rproxy_setup_sites:
  - server_name: auth.refol.us
    port: 4180
    proxy_pass: "http://{{ global_ip_addresses['rproxy-0'] }}"
    allow_list:
      - 192.168.0.0/24
      - 192.168.2.0/24
      - 24.105.250.200
      - 70.107.117.124
    restricted: false
    enable: false
