---
galaxy_info:
  author: Frank Refol
  role_name: lidarr_setup
  description: >
    Installs and configures Lidarr on Debian/Ubuntu systems.
    It uses a container distributed by [linuxserver](https://hub.docker.com/r/linuxserver/lidarr).
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - noble
