$ANSIBLE_VAULT;1.1;AES256
39663264363966333435633736373030356438396531356536653838633461653561303266323435
6634353239623732626163613233346336623563633931610a653838616365343134643665623832
66363137396462666238626134646665626330663930363234326333306139306139653362616163
3264653639363630320a333834623935313565613830393461393730643032623261313530313832
64393166653434643634623231376461373434356235336166643165666436633065613038383564
36346535666136633938313564333566663034393432336337633631346637386263376562383130
38363834653534333364353361303935636334643037653431376539326237653561333436643636
38656231376366336334366531383537623134666631386233313062343661653636663139633531
63306666636264306338616230353666386634633039646232356238613239653336323136393033
31633161646464623833616233353733643661393265353337343063366335303535353030326136
35346537663463643933616161626139663932333035326261346637346366643761386565323238
36393838663164306531643934353036383036636139316635393164346133653262366633333537
34353230653561643861613230366532643637323738653839313131393931323837613966346366
66323764613332396566323838353664666364306532303936363139326666636136346561613562
34366265393737343362616664323832626430333666613639353634373865396538373136643437
64356463346432396236633261396135643164336232326130363639303730316139643439636339
36663763363166323330303164343463393361633933356162303961393333653835323261353535
34386433623464653764356562613634323766323233626230353962653531323366653039366366
35343334613264363061383231386137623031303661396235353236656561613233626463323038
64373264303436636336643566636235666530306363633966653836343634313834313432636633
30646433336230333132306161323966613330336665393531613537303332656561336132393462
3139626564656234623139393365643938643365313832356534
