---

# Purpose: Install required Python 3 modules for Ansible operation

- name: Install Ansible Python Modules
  hosts: vms, synology
  gather_facts: true
  become: true
  tasks:
    - name: Import install_python_modules.yml from ansible_setup role
      ansible.builtin.import_role:
        name: ansible_setup
        tasks_from: install_python_modules.yml
