---

# Purpose: Backup Sonarr database to NFS share.

- name: Backup Sonarr database to NFS share
  hosts: pgdb
  become: true
  roles:
    - global

  tasks:
    - name: Import database_backup.yml from sonarr_setup role
      ansible.builtin.import_role:
        name: sonarr_setup
        tasks_from: database_backup.yml