---

# Purpose: Installs Calibre application.

- name: Deploy Calibre
  hosts: calibre
  become: true
  roles:
    - global
    - python3
    - users
    - autofs
    - docker_setup
    - calibre_setup
