---

# Purpose: Starts Sabnzbd service.

- name: Start sabnzbd
  hosts: sabnzbd
  become: true
  gather_facts: true
  roles:
    - global

  tasks:
    - name: Import sabnzbd_setup role start task
      ansible.builtin.import_role:
        name: sabnzbd_setup
        tasks_from: start
