---

# Purpose: Stops all media services

- name: Stop lidarr
  ansible.builtin.import_playbook: stop_lidarr.yml

- name: Stop radarr
  ansible.builtin.import_playbook: stop_radarr.yml

- name: Stop sonarr
  ansible.builtin.import_playbook: stop_sonarr.yml

- name: Stop sabnzbd
  ansible.builtin.import_playbook: stop_sabnzbd.yml

