---
galaxy_info:
  author: Frank Refol
  role_name: lazylibrarian_setup
  description: >
    Installs and configures LazyLibrarian on Debian/Ubuntu systems.
    It uses a Docker image distributed by [linuxserver](https://hub.docker.com/r/linuxserver/lazylibrarian).
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - noble
