---
galaxy_info:
  role_name: node_exporter_setup
  author: Francis Refol
  description: Installs Prometheus Node Exporter
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - bionic
        - focal
dependencies:
  - role: global
