$ANSIBLE_VAULT;1.1;AES256
62636539386439346638343431396263633939396561396562373933323831373339356139336662
3137323963633335623334626163616265316562623863380a333261633466323764313866616537
61323666666530336532303938663531643164383636306466663535303439396633613438663234
6564303766396463380a663931646166633336656633626565626138623862373766623761313463
37383365336664386538353064626331343138343962306163313535636632383732613733323137
30313139323031646564633932633136336366613331663734353031393133303634616636336265
63393865343462623033333339373463653861363830633766346631653632643139643534613663
32616330303238323835373338316439363364663038636361663531396538353435316264306433
37343837663137396437363332383636313861303366653765353938613332616337663233383936
33623638383465623136613130646432323964646664353266623631626563653838306663646630
39373134616366333565396465346433353264613830373664393565333562633033656463356564
36323432663162366239393631626239376535353835633263636534393630323633393639353136
62643865343933353665313836383463393665616236333037636239313363323931363964373232
37396233626130303438323133386638656661346266636538336665303439353137623061623836
35383237386634643230303666303933393434323365373966653666366164646233633337616434
33383739323762666132633730326364613231653866386131623661613262656338643464636163
34666265336635326130373261386139613830323031313435366138626264613130366134626331
37613761373834326131353661633762663739333031633765363166633834633330656366303733
39306561373866376530383463313536323164343932313630333733336263616462343161343264
36303939363065326462376237373661363964326163383930313966326636616337393530633730
66633931303463333133343265393937336439373839303735643361616638366538353563663862
65653036316264393838363532663930326538643038303030653631653132646362643461653831
336538343961376363303932346465393033
