---
galaxy_info:
  role_name: oauth2_proxy
  author: Frank Refol
  description: Install and configure OAuth2 Proxy.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - noble
dependencies:
  - role: redis_setup
  - role: entra_id_oauth2
