---
galaxy_info:
  author: Frank
  role_name: bedrock_setup
  description: Installs Minecraft Bedrock Server on Linux systems.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
    - name: Debian
      versions:
        - "11"
        - "12"
