---
galaxy_info:
  author: Frank Refol
  description: Configures entra_id settings for oAuth2-enabled sites.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
