---

vms_config:
  agent: "1"
  sockets: 1
  cores: "2"
  cpu: host
  memory: 2048
  scsihw: virtio-scsi-single
  storage: local
  net0: "virtio,bridge=vmbr0"
  vga: serial0
  serial: socket

rproxy_setup_sites:
  - server_name: ha.refol.us
    port: 8123
    proxy_pass: "http://{{ global_ip_addresses['ha-0'] }}"
    allow_list:
      - 192.168.0.0/24
      - 192.168.2.0/24
      - 24.105.250.200
      - 70.107.117.124
    restricted: false
    enable: true

home_assistant_setup_version: "16.3"
