---
galaxy_info:
  author: Frank Refol
  role_name: home_assistant_setup
  description: Installs Home Assistant using its QCOW2 image on a Proxmox VE host.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - noble
