---
galaxy_info:
  author: Frank Refol
  role_name: linux_updates
  description: The linux role contains tasks related to updating Linux updates.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - noble
