---
galaxy_info:
  role_name: ansible_node
  author: Francis Refol
  description: Configures a node to be used as an Ansible control node.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - bionic
        - focal
