$ANSIBLE_VAULT;1.1;AES256
38306637373231636265363336623837323831323063353234333437333230653035313535643030
3938323935656561643739346564346163393936353965330a353739613536366136363035306138
32336538346331313532633932383730303736636461333465353132326337353161383463383364
3366643661613863620a366563613862313565303232323564646337373036396265636466323962
32343035333765343861306134306638643961333466623632633966323632306238653135393636
34353236616561303665643130636662616138396438333437646262316566383536363030646664
37396235613865303231353234336435313034386662396261613436356362653337613661303466
38373930356233323330616231343261633439323664353334333830663037303935326361313166
63373137303039656363393064383863666563626430643131613565633735353362
