---

sabnzbd_setup_version: 4.5.3
sabnzbd_setup_config_dir: "/config"
sabnzbd_setup_port: 8080

sabnzbd_setup_mount_point: /nfs/backups
sabnzbd_setup_backup_prefix: "sabnzbd_"
sabnzbd_setup_backup_filename: "{{ sabnzbd_setup_backup_prefix }}{{ ansible_date_time.date }}.sqlc"
sabnzbd_setup_backups_dir: "{{ sabnzbd_setup_config_dir }}/sabnzbd"
sabnzbd_setup_backup_path: "{{ sabnzbd_setup_backups_dir }}/{{ sabnzbd_setup_backup_filename }}"

# Values for sabnzbd.ini
# sabnzbd_setup_login_user: see vault
# sabnzbd_setup_login_password: see vault
# sabnzbd_setup_api_key: see vault
# sabnzbd_setup_nzb_key: see vault
sabnzbd_setup_download_dir: /incomplete-downloads
sabnzbd_setup_complete_dir: /downloads
sabnzbd_setup_local_network_ranges:
  - 192.168.2.0/24
sabnzbd_setup_servers:
  - name: news.easynews.com
    displayname: news.easynews.com
    host: news.easynews.com
    port: 563
    timeout: 60
    username: "{{ sabnzbd_setup_easynews_login }}"
    password: "{{ sabnzbd_setup_easynews_password }}"
    connections: 60
    ssl: 1
    ssl_verify: 3
    ssl_ciphers: ""
    enable: 1
    required: 0
    optional: 0
    retention: 0
    expire_date: ""
    quota: ""
    usage_at_start: 0
    priority: 0
    notes: ""
  - name: news.newsdemon.com
    displayname: news.newsdemon.com
    host: news.newsdemon.com
    port: 563
    timeout: 60
    username: "{{ sabnzbd_setup_newsdemon_login }}"
    password: "{{ sabnzbd_setup_newsdemon_password }}"
    connections: 50
    ssl: 1
    ssl_verify: 3
    ssl_ciphers: ""
    enable: 1
    required: 0
    optional: 0
    retention: 0
    expire_date: ""
    quota: ""
    usage_at_start: 0
    priority: 0
    notes: ""
  - name: "news.giganews.com"
    displayname: "news.giganews.com"
    host: "news.giganews.com"
    port: 443
    timeout: 60
    username: "{{ sabnzbd_setup_giganews_login }}"
    password: "{{ sabnzbd_setup_giganews_password }}"
    connections: 100
    ssl: 1
    ssl_verify: 3
    ssl_ciphers: ""
    enable: 1
    required: 0
    optional: 0
    retention: 0
    expire_date: ""
    quota: ""
    usage_at_start: 0
    priority: 0
    notes: ""
