---
galaxy_info:
  role_name: ombi_setup
  author: Frank Refol
  description: >
    Ombi Setup installs and configures an Ombi Docker container.
    It uses a Docker image distributed by [linuxserver](https://hub.docker.com/r/linuxserver/ombi)
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - noble
dependencies:
  - role: redis_setup
