---

# defaults file for vm

vms_proxmox_node: pve-0
vms_autoinstall: false
vms_additional_packages: []
vms_name: "{{ name | default(inventory_hostname) }}"
vms_set_to_template: false
vms_clone_host: 192.168.2.199
vms_ip_address_configured: false
vms_clone: false

vms_pve_tls_insecure: true
