---
galaxy_info:
  author: Frank
  role_name: certbot_setup
  description: >
    It deploys certbot following instructions documented in https://certbot.eff.org/instructions?ws=nginx&os=pip.
    Target hosts must be in a group named *[certbot]* in its inventory. Certbot is used to obtain SSL/TLS
    certificates from Let's Encrypt.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
    - name: Debian
      versions:
        - "11"
        - "12"
