---

# Purpose: Deploy Python3 on python hosts.

- name: Install Python3
  hosts: python
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - python3
