---

# Purpose: Deploy OAuth2 Proxy with Entra ID as the identity provider

- name: Deploy OAuth2 Proxy
  hosts: oauth2_proxy
  gather_facts: true
  become: true
  become_user: root
  roles:
    - global
    - entra_id_oauth2
    - redis_setup
    - oauth2_proxy_setup
