---
galaxy_info:
  author: Frank Refol
  role_name: autofs
  description: Installs and configures autofs on Debian/Ubuntu.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
