---

# Purpose: Check disk space on Linux hosts

- name: Check disk space
  hosts: linux
  gather_facts: false
  tasks:
    - name: Check disk space (df)
      ansible.builtin.command: df -h /
      register: disk_space
      changed_when: false

    - name: Print disk space
      ansible.builtin.debug:
        msg: "{{ disk_space.stdout_lines }}"
