---
galaxy_info:
  role_name: sabnzbd_setup
  author: Frank Refol
  description: >
    Installs and configures a Sabnzbd Docker container. It uses a Docker image
    distributed by [linuxserver](https://hub.docker.com/r/linuxserver/sabnzbd).
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - bionic
        - focal
dependencies:
  - role: global
  - role: users
  - role: autofs
  - role: docker_setup
