---

global_ip_addresses:
  ansible-0: 192.168.2.101
  ansible-1: 192.168.2.102
  semaphore-0: 192.168.2.110
  sonarr-0: 192.168.2.150
  lidarr-0: 192.168.2.151
  radarr-0: 192.168.2.152
  sabnzbd-0: 192.168.2.153
  ombi-0: 192.168.2.155
  tautulli-0: 192.168.2.157
  books-0: 192.168.2.160
  minecraft-1: 192.168.2.166
  pg-0: 192.168.2.170
  pg-1: 192.168.2.171
  pg-2: 192.168.2.172
  pg-3: 192.168.2.173
  pg-4: 192.168.2.174
  jenkins-0: 192.168.2.180
  redmine-0: 192.168.2.186
  graphite-0: 192.168.2.190
  prometheus-0: 192.168.2.192
  grafana-0: 192.168.2.195
  ubu24-template: 192.168.2.199
  pve-0: 192.168.2.200
  pve-1: 192.168.2.201
  pve-2: 192.168.2.202
  rproxy-0: 192.168.2.210
  rproxy-1: 192.168.2.211
  rproxy-2: 192.168.2.212
  plex-0: 192.168.2.220
  synology-0: 192.168.2.240
  truenas-01: 192.168.2.250
  ad0: 192.168.2.251
  dns-0: 192.168.2.252
  dns-1: 192.168.2.253
  pxe-0: 192.168.2.254
  util-0: 192.168.0.56

global_ip_address: "{{ global_ip_addresses[inventory_hostname] }}"
global_pihole_api_host: "{{ global_ip_addresses['dns-1'] }}"
