---
global_ansible_root_dir: "{{ playbook_dir | dirname | dirname }}"
global_terraform_root_dir: "{{ global_ansible_root_dir }}/terraform"
global_inventory_dir_name: "{{ inventory_dir | basename }}"
global_ip_addresses:
  ansible-0: 192.168.20.101
  ansible-1: 192.168.20.102
  semaphore-0: 192.168.20.110
  sonarr-0: 192.168.20.150
  lidarr-0: 192.168.20.151
  radarr-0: 192.168.20.152
  sabnzbd-0: 192.168.20.153
  ombi-0: 192.168.20.155
  tautulli-0: 192.168.20.157
  books-0: 192.168.20.160
  minecraft-1: 192.168.20.166
  pg-0: 192.168.20.170
  pg-1: 192.168.20.171
  pg-2: 192.168.20.172
  pg-3: 192.168.20.173
  pg-4: 192.168.20.174
  jenkins-0: 192.168.20.180
  ha-0: 192.168.2.182
  redmine-0: 192.168.20.186
  prometheus-0: 192.168.20.192
  grafana-0: 192.168.20.195
  ubu24-template: 192.168.2.199
  pve-0: 192.168.2.200
  pve-1: 192.168.2.201
  pve-2: 192.168.2.202
  rproxy-0: 192.168.30.210
  rproxy-1: 192.168.20.211
  rproxy-2: 192.168.20.212
  plex-0: 192.168.2.220
  synology-0: 192.168.2.240
  truenas-01: 192.168.2.250
  ad0: 192.168.2.251
  dns-0: 192.168.20.252
  dns-1: 192.168.20.253
  pxe-0: 192.168.20.254
  util-0: 192.168.0.56

global_ip_address: "{{ global_ip_addresses[inventory_hostname] }}"
global_pihole_api_host: "{{ global_ip_addresses['dns-1'] }}"

global_oauth2_proxy_ports:
  code.refol.us: 4180
  lidarr.refol.us: 4181
  radarr.refol.us: 4182
  sonarr.refol.us: 4183
  sabnzbd.refol.us: 4184
  lazy.refol.us: 4185
  catalog.refol.us: 4186

global_oauth2_proxy_metrics_ports:
  code.refol.us: 9100
  lidarr.refol.us: 9101
  radarr.refol.us: 9102
  sonarr.refol.us: 9103
  sabnzbd.refol.us: 9104
  lazy.refol.us: 9105
  catalog.refol.us: 9106
