---
galaxy_info:
  author: Frank Refol
  role_name: graphite_setup
  description: Installs and configures Graphite on Debian/Ubuntu systems.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - noble
