---
galaxy_info:
  role_name: semaphoreui_setup
  author: Frank Refol
  description: Installs and configures [Semaphore UI](https://docs.semaphoreui.com/).
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - bionic
        - focal
