---
galaxy_info:
  role_name: aws_cli
  author: Francis Refol
  description: Installs and configures AWS CLI.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - bionic
        - focal
