---
galaxy_info:
  author: Frank Refol
  role_name: minecraft_setup
  description: >
    Installs Minecraft Server on Ubuntu and Debian systems (https://www.minecraft.net/en-us/download/server).
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
    - name: Debian
      versions:
        - "11"
        - "12"
dependencies:
  - role: java_setup
