---

- name: Include get_vms_vmid tasks
  ansible.builtin.include_tasks: "get_vms_vmid.yml"

- name: Include get_vms_proxmox_node tasks
  ansible.builtin.include_tasks: "get_vms_proxmox_node.yml"
  
- name: Stop VM
  ansible.builtin.uri:
    url: 'https://{{ global_proxmox_api_host }}:8006/api2/json/nodes/{{ vms_proxmox_node }}/qemu/{{ vms_vmid }}/status/stop'
    method: POST
    headers:
      Authorization: "PVEAPIToken={{ global_proxmox_api_user }}!{{ global_proxmox_api_token_id }}={{ global_proxmox_api_token }}"
    follow_redirects: safe
    validate_certs: false
  register: result
  delegate_to: localhost
  when: vms_vmid is defined

- name: Make sure virtual machine is really stopped
  ansible.builtin.uri:
    url: 'https://{{ global_proxmox_api_host }}:8006/api2/json/nodes/{{ vms_proxmox_node }}/qemu/{{ vms_vmid }}/status/current'
    method: Get
    headers:
      Authorization: "PVEAPIToken={{ global_proxmox_api_user }}!{{ global_proxmox_api_token_id }}={{ global_proxmox_api_token }}"
    follow_redirects: safe
    validate_certs: false
  register: vms_status_result
  retries: 5
  delay: 5
  until: vms_status_result.json.data.status == "stopped"
  delegate_to: localhost
  when: vms_vmid is defined

- name: Show vms_status_result
  debug:
    var: vms_status_result.json.data.status
