---
dependencies: []

galaxy_info:
  author: Frank Refol
  description: Install and configure Microsoft repository for VSCode.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - "20.04"
        - "22.04"
