---
galaxy_info:
  role_name: docker_service_deploy
  author: Frank Refol
  description: >
    Ansible role to deploy and manage Docker services using Docker Compose,
    with configuration templating and optional pre/post deployment hooks.
    This role is designed to be reusable for various Docker services.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - bionic
        - focal
dependencies: []
