---

oauth2_proxy_setup_version: "7.13.1"
oauth2_proxy_setup_download_tgz_file: "oauth2-proxy-v{{ oauth2_proxy_setup_version }}.linux-amd64.tar.gz"
oauth2_proxy_setup_download_url: |
  "https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v{{ oauth2_proxy_setup_version }}/{{ oauth2_proxy_setup_download_tgz_file }}"
oauth2_proxy_setup_config: /etc/oauth2-proxy/oauth2-proxy.cfg
oauth2_proxy_setup_bin: /usr/local/bin/oauth2-proxy
