---
galaxy_info:
  author: Frank
  role_name: code_server
  description: Installs and configures code server.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
    - name: Debian
      versions:
        - "11"
        - "12"
