---

# Purpose: Creates snapshots of virtual machines.

- name: Create snapshot
  hosts: vms
  gather_facts: false
  roles:
    - global

  tasks:
    - name: Import snapshot tasks from vms role
      ansible.builtin.import_role:
        name: vms
        tasks_from: snapshot_create
