$ANSIBLE_VAULT;1.1;AES256
36633139653837313339633862306236313532626135616566613765616230653361356439636431
6266336339666634353863333637376364613764306263390a656363323265616365636530646362
36636231626462346363323864623736333937313931386665323165623531303233336132336433
3534623961653731360a326137363731306630643530656433356337633962656634643464303632
38626434616364663530366337616262393966633837316437303730326330393661363564663866
66333566653865633263323337666163376462653164373737663132373130323365393262306533
39636438363564333631633637386339363735376638656538666235386239643839646330313538
39646365326663333164383935356638353734616339393566363034303939376238376365313066
32353934343863656637376266323039313632663165323966656130646438323431333061383833
66366133643464373762646231646232613936303938343036383435623162346330613764623763
38656362356536333464633066643465336232613863326230663562386266353062613164393336
33343636633237626639393733326336616538306162653230623562363232356231356262313530
63303931366539316364303531666533633131656235373731393133363864633836303139346161
64313530376363376336616663663432653835626161313937643034383334643261613734666265
31396535333965656535393636383836333636336661666639376666396233393262383936666163
30333330666435333031306339363339633230366464323035336234613265313165303061303537
62613364333030316236343532303038393032363931346662623737306563313965353937643433
36306634306462626665383132373563623538626336373462356465613736663037316233373563
37333238393135653634363237356136316231333932303237646632323038613861393231636238
64626535366334636537356465356265636230306362303962383838663333613333343366663061
34663539663932633936636139393163333132313865376230613336616538366464383538386630
39383934313636663832383337336631393264333331636534323436303037353832316135656532
62393365356266333162633766633163353363666232303266386233353762653031636661633238
39616636623031366166656364666164386133353263623835326561323331633262346635303232
61323365663739396230366236323736343237346338336564386333323935303233353431623335
61353632666462316332373338656336336430366665346636333765623031373764653531323561
39633862366665653535323839643830663463313539326139396366396633333836376535376537
31313266646639636437346639636565346263643631336262666563373163653331646532643631
35316463313032643336386133376161336233303131383933633136343733363764353434336566
62303333353437363637613264666539386162333530303230613938306134386634616631653139
35396361666631393037376362316439666266316663623037353166306231633764666366336637
65646665616564333135343865663934663439373432353964316164316132336232663638393332
66323161386363306238306232626232646466336336343535363939393631376566
