---

# https://github.com/Tautulli/Tautulli/wiki/Installation#docker
# https://hub.docker.com/r/linuxserver/tautulli

- name: Deploy Tautulli Docker Service
  ansible.builtin.import_role:
    name: docker_service_deploy
  vars:
    docker_service_deploy_config_dir: "{{ tautulli_setup_config_dir }}"
    docker_service_deploy_backups_dir: "{{ tautulli_setup_backups_dir }}"
    docker_service_deploy_compose_template: "docker-compose.yml.j2"
    docker_service_deploy_container_name: "tautulli"
