---
galaxy_info:
  role_name: plex_exporter_setup
  author: Francis Refol
  description: Provides tasks to install and configure prometheus-plex-exporter (https://github.com/jsclayton/prometheus-plex-exporter).
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - bionic
        - focal
