---

# Purpose: Installs and configures Tp-Link Omada Controller

- name: Install and configure Tp-Link Omada Controller
  hosts: omada
  become: true
  gather_facts: true
  roles:
    - global
    - java_setup
    - mongodb_setup
    - oc_setup
