---

# Purpose: Creates a VM template using cloud-init on the specified Proxmox node.

- name: Create a Template
  hosts: template
  gather_facts: false
  become: true
  roles:
    - global
    - role: cloudinit
      delegate_to: "{{ cloudinit_proxmox_node }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3
