---

# Purpose: Deploys Tautulli media tracking service with necessary configurations and NFS mounts.

- name: Deploy Tautulli
  hosts: tautulli
  become: true
  gather_facts: false
  roles:
    - global
    - users
    - docker_setup
    - tautulli_setup
    - role: autofs
      vars:
        autofs_nfs_mounts:
          - mount_name: backups
            server: 192.168.2.250:/mnt/Data/backups_ex
            mount_options: -rw,relatime,hard,rsize=1048576,wsize=1048576,proto=tcp,timeo=600,retrans=2,sec=sys
