---
dependencies: []

galaxy_info:
  author: Frank Refol
  role_name: wikipedia_setup
  description: Deploys and configures a Wikipedia instance using MediaWiki.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - "20.04"
        - "22.04"
