---
galaxy_info:
  role_name: windows_ansible_node
  author: Francis Refol
  description: Bootstraps a Windows host to be managed by Ansible over WinRM.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - 2016
        - 2019
        - 2022
