---

# Purpose: Sets up Semaphore UI application on semaphore hosts.
# It configures the Semaphore using the values in the
# semaphoreui_setup_projects variable. This playbook assumes
# that Semaphore UI has been installed.

- name: Setup Semaphore UI
  hosts: semaphore
  gather_facts: true
  become: true
  tasks:
    - name: Import semaphoreui_setup role setup tasks
      ansible.builtin.import_role:
        name: semaphoreui_setup
        tasks_from: setup_main.yml
