---
galaxy_info:
  role_name: python3
  author: Frank Refol
  description: >
    Installs Python 3 from the Python Software Foundation (PSF) repository.
    There is also an alternate option is to compile Python 3 from source.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - bionic
        - focal

