---
galaxy_info:
  role_name: oc_setup
  author: Frank Refol
  description: Install and configure TP-Link Omada Controller on Ubuntu systems.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - noble
dependencies:
  - role: redis_setup
