---

# Purpose: Deploy and configure VSCode Server on target hosts

- name: Install and configure code-server
  hosts: vscode
  become: true
  gather_facts: true
  roles:
    - global
    - vscode_server
