---

semaphoreui_setup_projects_templates:
  "Home Lab":
    - name: "Backup Semaphore Database"
      playbook: "playbooks/semaphoreui/backup_db.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "semaphore"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Backups"
      environment: "Empty"
    - name: "Backup Ombi Database"
      playbook: "playbooks/ombi/backup_db.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "ombi"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Backups"
      environment: "Empty"
    - name: "Backup Lidarr Database"
      playbook: "playbooks/services/backup_lidarr_db.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Backups"
      environment: "Empty"
    - name: "Backup Sonarr Database"
      playbook: "playbooks/services/backup_sonarr_db.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Backups"
      environment: "Empty"
    - name: "Backup Radarr Database"
      playbook: "playbooks/services/backup_radarr_db.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Backups"
      environment: "Empty"
    - name: "Backup Tautulli Database"
      playbook: "playbooks/tautulli/backup_db.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "tautulli"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Backups"
      environment: "Empty"
    - name: "Backup Plex"
      playbook: "playbooks/plex/backup_plex.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "plex"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Backups"
      environment: "Empty"
    - name: "Backup Grafana Database"
      playbook: "playbooks/grafana/backup_db.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "grafana"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Backups"
      environment: "Empty"
    - name: "Backup Prometheus Database"
      playbook: "playbooks/prometheus/backup_db.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "prometheus"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Backups"
      environment: "Empty"
    - name: "Backup Redmine Database"
      playbook: "playbooks/redmine/backup_db.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "redmine"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Backups"
      environment: "Empty"
    - name: "Setup Semaphore"
      playbook: "playbooks/semaphoreui/setup_semaphoreui.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "semaphore"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Semaphore"
      environment: "Empty"
    - name: "Request Certificates for lab.refol.us"
      playbook: "playbooks/certs/generate_certs.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "redmine"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Certs"
      environment: "Empty"
    - name: "Stage Certificates for lab.refol.us"
      playbook: "playbooks/certs/stage_certs.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "redmine"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Certs"
      environment: "Empty"
    - name: "Request Certificates for all hosts"
      playbook: "playbooks/certs/generate_all_certs.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "rproxy"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Certs"
      environment: "Empty"
    - name: "Stage Certificates for all hosts"
      playbook: "playbooks/certs/stage_all_certs.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "rproxy"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Certs"
      environment: "Empty"
    - name: "Distribute Certificates to Proxmox Nodes"
      playbook: "playbooks/certs/distribute_pve_certs.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "pve"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Certs"
      environment: "Empty"
    - name: "Deploy Sonarr"
      playbook: "playbooks/services/deploy_sonarr.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Deploy Radarr"
      playbook: "playbooks/services/deploy_radarr.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Deploy Lidarr"
      playbook: "playbooks/services/deploy_lidarr.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Deploy Calibreweb"
      playbook: "playbooks/services/deploy_calibreweb.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Deploy Calibre"
      playbook: "playbooks/services/deploy_calibre.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Deploy Lazy Librarian"
      playbook: "playbooks/services/deploy_lazylibrarian.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Deploy Sabnzbd"
      playbook: "playbooks/services/deploy_sabnzbd.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Deploy Redmine"
      playbook: "playbooks/redmine/deploy_redmine.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "redmine"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Deploy Plex"
      playbook: "playbooks/plex/deploy_plex.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "plex"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Deploy Bedrock"
      playbook: "playbooks/minecraft/deploy_bedrock.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "minecraft"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Deploy Ombi"
      playbook: "playbooks/ombi/deploy_ombi.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "ombi"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Deploy Code Server"
      playbook: "playbooks/deploy_code_server.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "ansible"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
    - name: "Bedrock Update Check"
      playbook: "playbooks/minecraft/check_bedrock_version.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "minecraft"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Update Checks"
      environment: "Empty"
    - name: "SemaphoreUI Update Check"
      playbook: "playbooks/semaphoreui/check_semaphore_version.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "semaphore"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Update Checks"
      environment: "Empty"
    - name: "Reboot Sonarr"
      playbook: "playbooks/vms/reboot_vm.yml"
      app: "ansible"
      arguments: "[\"-k -l sonarr\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Reboots"
      environment: "Empty"
    - name: "Reboot Radarr"
      playbook: "playbooks/vms/reboot_vm.yml"
      app: "ansible"
      arguments: "[\"-k\",\"-l radarr\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Reboots"
      environment: "Empty"
    - name: "Reboot Lidarr"
      playbook: "playbooks/vms/reboot_vm.yml"
      app: "ansible"
      arguments: "[\"-k\",\"-l lidarr\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Reboots"
      environment: "Empty"
    - name: "Reboot Sabnzbd"
      playbook: "playbooks/vms/reboot_vm.yml"
      app: "ansible"
      arguments: "[\"-k\",\"-l sabnzbd\"]"
      inventory: "services"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Reboots"
      environment: "Empty"
    - name: "Reboot Plex"
      playbook: "playbooks/vms/reboot_vm.yml"
      app: "ansible"
      arguments: "[\"-k\",\"-l plex\"]"
      inventory: "plex"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Reboots"
      environment: "Empty"
    - name: "Reboot Reverse Proxy Servers"
      playbook: "playbooks/vms/reboot_vm.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "rproxy"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Reboots"
      environment: "Empty"
    - name: "Mirror Redmine Wiki"
      playbook: "playbooks/redmine/mirror_wiki.yml"
      app: "ansible"
      arguments: "[\"-k\"]"
      inventory: "redmine"
      credentials:
        - "Ansible vault password"
      repository: "Ansible"
      view: "Deploys"
      environment: "Empty"
