---

# Purpose: Check latest Minecraft Java Edition version on Minecraft hosts

- name: Enumerate latest version of Minecraft Java Edition
  hosts: minecraft
  become: true
  roles:
    - playwright

  tasks:
    - name: Import get_minecraft_version.yml from minecraft_setup role
      ansible.builtin.import_role:
        name: minecraft_setup
        tasks_from: get_minecraft_version.yml