---

# Purpose: Check latest Bedrock version on Bedrock hosts

- name: Enumerate latest version of Bedrock
  hosts: bedrock
  become: true
  roles:
    - playwright

  tasks:
    - name: Import get_bedrock_version.yml from bedrock_setup role
      ansible.builtin.import_role:
        name: bedrock_setup
        tasks_from: get_bedrock_version.yml
