---

lazylibrarian_setup_config_dir: "/config/lazylibrarian"
lazylibrarian_setup_version: 0c862d0f
lazylibrarian_setup_mount_point: /nfs/backups
lazylibrarian_setup_backup_prefix: "lazy_"
lazylibrarian_setup_backup_filename: "{{ lazylibrarian_setup_backup_prefix }}{{ ansible_date_time.date }}.sqlc"
lazylibrarian_setup_backups_dir: "{{ lazylibrarian_setup_mount_point }}/lazy"
lazylibrarian_setup_backup_path: "{{ lazylibrarian_setup_backups_dir }}/{{ lazylibrarian_setup_backup_filename }}"
