---
galaxy_info:
  role_name: ruby_setup
  author: Frank Refol
  description: >
    The ruby_setup role builds and install Ruby from it's
    [https://www.ruby-lang.org/en/downloads/](source code).
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - bionic
        - focal

